# Generated by Django 4.2.6 on 2023-10-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=True, verbose_name='Is employee'),
        ),
    ]
