# Generated by Django 4.2.6 on 2023-10-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_user_is_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
