# Generated by Django 4.2.6 on 2023-10-29 10:26

from django.db import migrations, models
import cars.models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='FechaSubasta',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='año',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='cilindrada',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='km',
            field=models.IntegerField(default=190000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='marca',
            field=models.CharField(default='Audi', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='modelo',
            field=models.CharField(default='A3', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='precioVenta',
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
    ]
