# Generated by Django 4.2.6 on 2023-10-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_task_fechasubasta_task_año_task_cilindrada_task_km_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='año',
            new_name='ano',
        ),
    ]
