# Generated by Django 4.2.6 on 2023-10-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_año_task_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ano',
            field=models.CharField(max_length=4),
        ),
    ]
