# Generated by Django 4.2.6 on 2023-10-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_task_cilindrada_alter_task_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='TestFile', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='km',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='car',
            name='precioVenta',
            field=models.CharField(max_length=6),
        ),
    ]
