# Generated by Django 4.2.6 on 2023-10-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_task_image_alter_task_km_alter_task_precioventa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='carImage',
        ),
    ]
