# Generated by Django 4.2.6 on 2023-10-31 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_rename_image_task_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='carImage',
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='coches/')),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='cars.car')),
            ],
        ),
    ]
