# Generated by Django 4.2.6 on 2023-11-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_ano_alter_car_cilindrada_alter_car_km_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='pago_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='car_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='cars.car'),
            preserve_default=False,
        ),
    ]
