# Generated by Django 4.2.6 on 2023-11-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_car_matricula_pago_pagado_pago_transaccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created',
        ),
        migrations.RemoveField(
            model_name='car',
            name='datecompleted',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='important',
        ),
        migrations.RemoveField(
            model_name='car',
            name='title',
        ),
    ]
