# Generated by Django 4.2.6 on 2023-11-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_remove_car_created_remove_car_datecompleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='precioVenta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
