# Generated by Django 4.2.6 on 2023-11-05 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_car_precioventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='pago_id',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='car_id',
        ),
        migrations.AddField(
            model_name='car',
            name='pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car', to='cars.pago'),
        ),
    ]
