# Generated by Django 4.2.6 on 2023-11-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_remove_car_pago_id_remove_pago_car_id_car_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='pago',
        ),
        migrations.AddField(
            model_name='pago',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago', to='cars.car'),
        ),
    ]
