# Generated by Django 4.2.6 on 2023-11-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_remove_car_pago_pago_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
