# Generated by Django 4.2.6 on 2023-11-07 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0022_alter_puja_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puja',
            name='car',
        ),
        migrations.RemoveField(
            model_name='puja',
            name='user',
        ),
        migrations.AddField(
            model_name='puja',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puja',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
